### ISSUE TITLE
Missing error markers for duplicate labels

### ISSUE THREAD

**Issue by rakshitkr** [CROSSINGTUD/CryptSL#9]
The CrySL rule editor doesn't display error markers when we have duplicate labels like below

```
c1: CipherInputStream(is, ciph1);
c2: CipherInputStream(is, ciph2);
c2: CipherInputStream(is, ciph3);
```

We get the following exception when compiling the rule
```
java.lang.ClassCastException: de.darmstadt.tu.crossing.cryptSL.impl.EventImpl cannot be cast to de.darmstadt.tu.crossing.cryptSL.SuperType
	at de.cognicrypt.crysl.reader.CrySLReaderUtils.stringifyMethodSignature(CrySLReaderUtils.java:65)
	at de.cognicrypt.crysl.reader.CrySLReaderUtils.dealWithAggregate(CrySLReaderUtils.java:41)
	at de.cognicrypt.crysl.reader.CrySLReaderUtils.resolveAggregateToMethodeNames(CrySLReaderUtils.java:56)
	at de.cognicrypt.crysl.reader.StateMachineGraphBuilder.addRegularEdge(StateMachineGraphBuilder.java:42)
	at de.cognicrypt.crysl.reader.StateMachineGraphBuilder.addRegularEdge(StateMachineGraphBuilder.java:38)
	at de.cognicrypt.crysl.reader.StateMachineGraphBuilder.process(StateMachineGraphBuilder.java:235)
	at de.cognicrypt.crysl.reader.StateMachineGraphBuilder.processHead(StateMachineGraphBuilder.java:334)
	at de.cognicrypt.crysl.reader.StateMachineGraphBuilder.buildSMG(StateMachineGraphBuilder.java:64)
	at de.cognicrypt.crysl.reader.CrySLModelReader.buildStateMachineGraph(CrySLModelReader.java:231)
	at de.cognicrypt.crysl.reader.CrySLModelReader.readRule(CrySLModelReader.java:167)
	at de.cognicrypt.crysl.reader.CrySLModelReader.readRules(CrySLModelReader.java:219)
	at de.cognicrypt.crysl.handler.StartupHandler$AfterBuildListener.resourceChanged(StartupHandler.java:60)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:290)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:153)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:365)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:157)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by kruegers** [comment]
Temporary fix [here](https://github.com/eclipse-cognicrypt/CogniCrypt/commit/c6c1942d8d8d31b98cb68554d04aeb42bc53c901).  Should be addressed in CryptSL project itself tho.

**Comment by rakshitkr** [comment]
Import these plugin projects in your *outer eclipse*
`de.cognicrypt.core`
`de.cognicrypt.crysl.handler`
`de.darmstadt.tu.crossing.CrySL`
`de.darmstadt.tu.crossing.CrySL.ide`
`de.darmstadt.tu.crossing.CrySL.ui`

Right click on `de.cognicrypt.core` and `Run As -> Eclipse Application`. This will open what we refer to as *inner eclipse*.

Import `JavaCryptographicArchitecture` project and open `CipherInputStream.crysl` file and make the below change
```
c1: CipherInputStream(is, ciph1); // line 1
c2: CipherInputStream(is, ciph2); // line 2
c2: CipherInputStream(is, ciph3); // line 3
```
Excepted : error markers at lines 2 & 3

**Comment by rakshitkr** [comment]
@anemonekk Please use the above instructions to reproduce this bug
